Adds Campaigns endpoint
DoSomething/phoenix-js pull request #12
Opened 2016-09-20 22:40 UTC by aaronschachter

#### What's this PR do?
Closes #11, using `callAction` on a new `phoenix-endpoint-campaigns` to implement `Campaigns.signup(id, data)` and `Campaigns.reportback(id, data)`.

Expected repeat Signup tests to fail, but they're not 😕. But that's good, because our tests pass, right? 😸 

#### Any background context you want to provide?

Tried adding [Nock](https://www.npmjs.com/package/nock) as a lightweight way to mock API tests in just our `campaigns.test.js`, but it threw errors for all other endpoints: 
> Error: Nock: No match for request POST https://staging.beta.dosomething.org/api/v1/users/get_member_count {}

Started looking into http://sinonjs.org/ and https://github.com/testdouble/testdouble.js per https://github.com/DoSomething/northstar-js/issues/11#issuecomment-246496549, but didn't seem necessary for merging this PR, as tests are running (and I've verified the data does show up in Phoenix)

#### Relevant tickets
Fixes #11

2016-09-21 14:07 UTC, sergii-tkachenko commented on lib/phoenix-endpoint-campaigns.js
> +        return Number(body);
The reason why your test doesn't fail is that `body` for the test is actually returned `false`.
Thus `Number('false')` [evaluates](**url**) to `NaN`.

However, [`NaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NaN) (stands for "not a number") **is**, in fact, a `Number`. Javascript :trollface:.

So it's totally valid to return a `Number` from Promise. We need to check the result for `NaN` and treat it as an error, throw an exception (see `parseResponse()`).

2016-09-21 14:09 UTC, sergii-tkachenko commented on lib/phoenix-endpoint-campaigns.js
> +      .then((response) => {
Let's move this parser (and the same below) to `this.parseNumberResponse()`.

2016-09-21 14:09 UTC, sergii-tkachenko commented on lib/phoenix-endpoint-campaigns.js
> +        return Number(body);
The reason why your test doesn't fail is that `body` for the test is actually returned `false`.
Thus `Number('false')` [evaluates](**url**) to `NaN`.

However, [`NaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NaN) (stands for "not a number") **is**, in fact, a `Number`. Javascript :trollface:.

So it's totally valid to return a `Number` from Promise. We need to check the result for `NaN` and treat it as an error, throw an exception (see `parseResponse()`).

2016-09-21 14:10 UTC, sergiitk requested changes

2016-09-21 15:44 UTC, sergii-tkachenko commented on lib/phoenix-endpoint-campaigns.js
> +        const body = this.parseNumberResponse(response);
I believe now you should be able to do

```js
.then(response => this.parseNumberResponse(response));
```

2016-09-21 15:46 UTC, sergiitk requested changes

2016-09-21 15:48 UTC, sergii-tkachenko commented on lib/phoenix-endpoint-campaigns.js
> +        const body = this.parseNumberResponse(response);
And the same for the `reportback()`.

2016-09-21 15:49 UTC, sergiitk approved these changes

2016-09-21 15:49 UTC, sergiitk requested changes
Sorry, approved it by an accident.

2016-09-21 18:27 UTC, sergii-tkachenko commented on test/helpers/test-helper.js
> +const nock = require('nock');
I think it'd be much better to include this to `bootstrap.test.js` instead.

2016-09-21 18:27 UTC, sergiitk requested changes

2016-09-21 23:07 UTC, aaronschachter commented
Whoops, I force pushed this branch (by rebasing with master to get latest) -- the commit that review requesting changes for can't find the changes any more (click on "View changes" when going to https://github.com/DoSomething/phoenix-js/pull/12#pullrequestreview-1012960).

@sergii-tkachenko not sure if you can approve PR as is or if I need to open up a new one.

2016-09-22 15:57 UTC, sergiitk requested changes
Good job! 👍

2016-09-22 15:58 UTC, sergiitk approved these changes
Agh. Meant to approve it.
Good job! 👍

2016-09-22 15:59 UTC, merged